
"""
Django settings for creworder_backend project.

Generated by 'django-admin startproject' using Django 4.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
CELERY_BROKER_URL = 'redis://localhost:6379/0'

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-l@!ajgx@)v#ip%5g^^2r*#f^wg9*a)a-m2(d#@oc7w7rw17fgp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
BASE_URL = "https://app.creworder.com"
ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    'app.creworder.com',  # Add this domain to the allowed hosts list
    'creworder.com',    # Add any other domains you need
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'rest_framework',
    'rest_framework.authtoken',
    'dj_rest_auth',
    'phonenumber_field',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'guardian',
    'corsheaders',
    'accounts',
    'emailsetup',
    'orders',
    'chat',
    'follow_up',
    'cloud_telephony',
    'lead_management',
    'shipment',
    'superadmin_assets',
    'django_extensions',
    'dashboard',
    'landing_page',
    'kyc',
    "django_celery_beat"
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'middleware.request_middleware.RequestMiddleware',
    'middleware.request_middleware.MaskNumberMiddleware',
    'middleware.sleep_kill_middleware.SleepQueryCleanerMiddleware'
]  

CORS_ALLOW_ALL_ORIGINS = True  # REMOVE or set to False

CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "https://creworder.com",
    "https://www.creworder.com",
]

# CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    "authorization",
    "content-type",
    "x-csrftoken",
    "accept",
    "origin",
    "user-agent",
    "x-requested-with",
    'no-cache',
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS"
]

CSRF_TRUSTED_ORIGINS = [
    "https://creworder.com",
    "https://www.creworder.com",
    "https://app.creworder.com",
    "http://localhost:3000",
]
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
    'guardian.backends.ObjectPermissionBackend'
)

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.BasicAuthentication',
        'accounts.authentication.CustomTokenAuthentication'
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 100,
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',  # Forces JSON responses
    ),
}

ROOT_URLCONF = 'creworder_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'creworder_backend.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {

    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'crew_crew_django',








        'USER': 'crew_admin',








        'PASSWORD': 'admin',
        'HOST': 'localhost',
        'PORT': '3306',
        'CONN_MAX_AGE': 240,  # Keep connection alive for 240 seconds
        'OPTIONS': {
        'init_command': "SET SESSION max_statement_time=200",  # 200 seconds (MariaDB only)
        }
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

SITE_ID = 1

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/


MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'
STATIC_URL = '/static/'
STATIC_ROOT = '/home/creworder.com/public_html/creworder_backend/staticfiles'
DATA_UPLOAD_MAX_NUMBER_FIELDS = 2000
# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
from logging.handlers import RotatingFileHandler

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'handlers': {
#         'rotating_file': {
#             'level': 'DEBUG',
#             'class': 'logging.handlers.RotatingFileHandler',
#             'filename': os.path.join(BASE_DIR, 'django_debug.log'),
#             'maxBytes': 1024 * 1024 * 5,  
#             'backupCount': 3,
#         },
#         'console': {
#             'level': 'DEBUG',
#             'class': 'logging.StreamHandler',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['rotating_file', 'console'],
#             'level': 'DEBUG',
#             'propagate': True,
#         },
#         'myapp': {
#             'handlers': ['rotating_file', 'console'],
#             'level': 'DEBUG',
#             'propagate': False,
#         },
#     },
# }
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
DATA_UPLOAD_MAX_NUMBER_FIELDS = 200000  # Or a higher value
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
FRONTEND_DOMAIN = "creworder.com"
SANDBOX_API_KEY = 'key_live_jLdOQIWhFZ0Vy4Ysto524DUvjnLamfGt'
SANDBOX_API_SECRET = 'secret_live_riAHC7MP2KQuSQsgirK0lKONJvXQ1KIg'
SANDBOX_HOST = 'https://api.sandbox.co.in'
SMS_API_KEY = "dqWOcbPzrncSkgX9"
SMS_SENDER_ID = "CrOrdr"
